// Generated by CoffeeScript 1.9.1
(function() {
  'use strict';
  var clonePlainObject, extname, swapFileNameExtension;

  extname = require('path').extname;

  swapFileNameExtension = function(pathFileName, newExtension) {
    return (pathFileName.substr(0, pathFileName.indexOf(extname(pathFileName)))) + "." + newExtension;
  };

  clonePlainObject = function(srcObj) {
    return JSON.parse(JSON.stringify(srcObj));
  };

  module.exports = {
    swapFileNameExtension: swapFileNameExtension,
    clonePlainObject: clonePlainObject
  };

}).call(this);
